# -*- coding: utf-8 -*-
"""Lecture Space.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uQqStWqALzqW2uEUk4Aur0_R58KbB96R
"""

# Commented out IPython magic to ensure Python compatibility.
import arviz as az
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import pymc as pm
import pytensor.tensor as pt

# %matplotlib inline

RANDOM_SEED = 8927
rng = np.random.default_rng(RANDOM_SEED)
az.style.use("arviz-darkgrid")


#----


data = pd.read_csv("https://github.com/dustywhite7/Econ8310/raw/master/DataSets/mariners2021.csv")
at_bats, hits = data[['at_bats', 'hits']].to_numpy().T


#----


N = len(hits)
player_names = data["name"]
coords = {"player_names": player_names.tolist()}


#----


with pm.Model(coords=coords) as baseball_model:
    phi = pm.Uniform("phi", lower=0.0, upper=1.0)

    kappa_log = pm.Exponential("kappa_log", lam=1.5)
    kappa = pm.Deterministic("kappa", pt.exp(kappa_log))

    theta = pm.Beta("theta", alpha=phi * kappa, beta=(1.0 - phi) * kappa, dims="player_names")
    y = pm.Binomial("y", n=at_bats, p=theta, dims="player_names", observed=hits)


#----


with baseball_model:
    theta_new = pm.Beta("theta_new", alpha=phi * kappa, beta=(1.0 - phi) * kappa)
    y_new = pm.Binomial("y_new", n=4, p=theta_new, observed=0)


#----


with baseball_model:
    idata = pm.sample(2000, tune=2000, chains=2, target_accept=0.95)

    # check convergence diagnostics
    assert all(az.rhat(idata) < 1.03)


#----


az.plot_trace(idata, var_names=["phi", "kappa"])


#----


az.plot_forest(idata, var_names="theta");

