digraph {\n\tsubgraph "cluster33,900" {\n\t\ty [label="y\n~\nBinomial" style=filled]\n\t\tp [label="p\n~\nDeterministic" shape=box]\n\t\tdistance [label="distance\n~\nData" shape=box style="rounded, filled"]\n\t\tdown [label="down\n~\nData" shape=box style="rounded, filled"]\n\t\tpasses [label="passes\n~\nData" shape=box style="rounded, filled"]\n\t\tlabel="33,900" labeljust=r labelloc=b style=rounded\n\t}\n\t"β_pass" [label="β_pass\n~\nNormal"]\n\t"β0" [label="β0\n~\nNormal"]\n\t"β_down" [label="β_down\n~\nNormal"]\n\t"β_distance" [label="β_distance\n~\nNormal"]\n\t"β0" -> p\n\tdistance -> p\n\t"β_down" -> p\n\tdown -> p\n\tpasses -> p\n\t"β_distance" -> p\n\t"β_pass" -> p\n\tp -> y\n}\n